; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
;src_dir =  ./src
build_dir = ./pioenvs
;lib_dir = ./piolib
lib_dir = ./Drivers
libdeps_dir = ./piolibdeps
;libdeps_dir = ${platformio.workspace_dir}\piolibdeps
;
;default_envs = lcr_meter_stm32f103c8
;default_envs = win_stm32f103c8_release
default_envs = win_stm32f103c8_debug

[env:lcr_meter_stm32f103c8]
platform = ststm32
board = genericSTM32F103C8
;board = bluepill_f103c8
board_build.f_cpu = 72000000L
board_build.ldscript = STM32F103C8TX_FLASH.ld
framework = stm32cube
upload_protocol = cmsis-dap
debug_tool = cmsis-dap
build_type = debug
board_build.stm32cube.custom_config_header = yes
board_build.stm32cube.system_file = yes
build_flags =
    -D DEBUG
    -D STM32F103xB
    -D USE_HAL_DRIVER
    -D USE_FULL_LL_DRIVER
    -save-temps=obj
    -fverbose-asm
;   -std=gnu++14
;   -std=gnu++17
;   -std=c++11
;   -std=c++14
;   -std=c++17
;   -std=c++20
;    -flto
    -fsingle-precision-constant
    -ffunction-sections            ; functions in their own sections
    -fdata-sections                ; data in their own sections
;    -fcyclomatic-complexity
    -fstack-usage
    -Wall                          ; all warnings
    -fno-exceptions                ; disable handling exceptions
;    -fno-threadsafe-statics        ; disable thread-safe init of local statoc objects
;    -fno-rtti
;    -fno-use-cxa-atexit
    -Wl,-u,_printf_float
    -Wl,-print-memory-usage
    -Wl,-Map,firmware.map
    -O0

[env:win_stm32f103c8_release]
platform = ststm32
board = genericSTM32F103C8
;board = bluepill_f103c8
board_build.mcu = stm32f103c8t6
board_build.f_cpu = 72000000L
board_build.ldscript = STM32F103C8_FLASH.ld
framework = stm32cube
upload_protocol = stlink
upload_flags = -c set CPUTAPID 0x2ba01477                 ; because they use a counterfeit STM32F103 on the PCB
build_type = release
board_build.stm32cube.custom_config_header = yes
board_build.stm32cube.system_file = yes
build_flags =
    -D RELEASE
    -D STM32F103xB
;    -D USE_HAL_DRIVER
    -D USE_FULL_LL_DRIVER
	-I ./Drivers/STM32F1xx_HAL_Driver/Inc/Legacy
	-I ./Drivers/STM32F1xx_HAL_Driver/Inc
	-I ./Drivers/STM32F1xx_HAL_Driver/Src
	-I ./Drivers/CMSIS/Include
    -I ./Drivers/CMSIS/Device/ST/STM32F1xx/Include
	-I ./src
    -save-temps=obj
    -fverbose-asm
;   -std=gnu++14
;   -std=gnu++17
;   -std=c++11
   -std=c++14
;   -std=c++17
;   -std=c++20
;    -flto
    -fsingle-precision-constant
    -ffunction-sections            ; functions in their own sections
    -fdata-sections                ; data in their own sections
;    -fcyclomatic-complexity
    -fstack-usage
    -Wall                          ; all warnings
    -fno-exceptions                ; disable handling exceptions
;    -fno-threadsafe-statics       ; disable thread-safe init of local static objects
;    -fno-rtti
;    -fno-use-cxa-atexit
    -specs=nano.specs
    -Wl,-u,_printf_float
    -Wl,-print-memory-usage
    -Wl,-Map,firmware.map
    -Wl,--gc-sections              ; discard unused sections
    -O3
extra_scripts = post:extra_script.py                      ; only if you want a compiled .hex file as well as the .bin file

[env:win_stm32f103c8_debug]
platform = ststm32
board = genericSTM32F103C8
;board = bluepill_f103c8
board_build.mcu = stm32f103c8t6
board_build.f_cpu = 72000000L
board_build.ldscript = STM32F103C8_FLASH.ld
framework = stm32cube
debug_tool = stlink
upload_protocol = stlink
upload_flags = -c set CPUTAPID 0x2ba01477                 ; because they use a counterfeit STM32F103 on the PCB
build_type = debug
board_build.stm32cube.custom_config_header = yes
board_build.stm32cube.system_file = yes
build_flags =
    -D DEBUG
    -D STM32F103xB
;    -D USE_HAL_DRIVER
    -D USE_FULL_LL_DRIVER
	-I ./Drivers/STM32F1xx_HAL_Driver/Inc/Legacy
	-I ./Drivers/STM32F1xx_HAL_Driver/Inc
	-I ./Drivers/STM32F1xx_HAL_Driver/Src
	-I ./Drivers/CMSIS/Include
    -I ./Drivers/CMSIS/Device/ST/STM32F1xx/Include
	-I ./src
	-save-temps=obj
    -fverbose-asm
;   -std=gnu++14
;   -std=gnu++17
;   -std=c++11
   -std=c++14
;   -std=c++17
;   -std=c++20
;    -flto
    -fsingle-precision-constant
    -ffunction-sections            ; functions in their own sections
    -fdata-sections                ; data in their own sections
;    -fcyclomatic-complexity
    -fstack-usage
    -Wall                          ; all warnings
    -fno-exceptions                ; disable handling exceptions
;    -fno-threadsafe-statics       ; disable thread-safe init of local static objects
;    -fno-rtti
;    -fno-use-cxa-atexit
    -g3                            ; max debug
    -specs=nano.specs
    -Wl,-u,_printf_float
    -Wl,-print-memory-usage
    -Wl,-Map,firmware.map
    -Wl,--gc-sections              ; discard unused sections
    -Og
extra_scripts = post:extra_script.py                        ; only if you want a compiled .hex file as well as the .bin file
debug_server =
	${platformio.packages_dir}/tool-openocd/bin/openocd.exe
	-s ${platformio.packages_dir}/tool-openocd/scripts
	-f interface\stlink.cfg
	-c "transport select hla_swd"
	-c "set CPUTAPID 0x2ba01477"
	-f target\stm32f1x.cfg
	-c "reset_config none"
